---
services:
  ingress:
    build: ingress
    image: localhost/composition/ingress
    init: true
    ports:
      - "[::]:8080:8080"
      - "[::]:8443:8443"
    volumes:
      - ../Containers/ingress-certs:/certs

  hellopaca:
    build: hellopaca
    image: localhost/composition/hellopaca
    init: true
