---
services:
  ingress:
    build: ingress
    image: localhost/composition/ingress
    init: true
    network_mode: host
    restart: on-failure
    volumes:
      - ../Containers/ingress/certs:/certs

  hellopaca:
    build: hellopaca
    image: localhost/composition/hellopaca
    init: true
    network_mode: host
    restart: on-failure

  rainbow:
    build: https://github.com/JockeTF/rainbow.git
    image: localhost/composition/rainbow
    init: true
    network_mode: host
    restart: on-failure
    volumes:
      - ../Containers/rainbow/assets:/assets

  torrent:
    build: torrent
    image: localhost/composition/torrent
    init: true
    network_mode: host
    restart: on-failure
    volumes:
      - ../Containers/torrent/state:/app
      - ../Prereleases:/prereleases
      - ../Fimfarchive:/releases
