---
services:
  ingress:
    build: ingress
    image: localhost/composition/ingress
    init: true
    ports:
      - "[::]:8080:8080"
      - "[::]:8443:8443"
    volumes:
      - ../Containers/ingress-certs:/certs

  fimfatracker:
    build: https://github.com/JockeTF/fimfarchive.git#:operations/tracker
    image: localhost/composition/fimfatracker
    init: true
    ports:
      - "[::]:6969:6969"

  hellopaca:
    build: hellopaca
    image: localhost/composition/hellopaca
    init: true
