---
services:
  ingress:
    build: ingress
    image: localhost/composition/ingress
    init: true
    ports:
      - "[::]:8080:8080"
      - "[::]:8443:8443"
    volumes:
      - ../Containers/ingress-certs:/certs

  fimfawebsite:
    build: https://github.com/JockeTF/fimfarchive.git#:operations/website
    image: localhost/composition/fimfawebsite
    init: true
    volumes:
      - ../Fimfarchive:/releases

  hellopaca:
    build: hellopaca
    image: localhost/composition/hellopaca
    init: true
