listen_ipv6 = true
listen_port = 8080
listen_port_tls = 8443
https_redirection_port = 443

[apps.localhost]
server_name = "localhost"

[[apps.localhost.reverse_proxy]]
upstream = [{ location = "hellopaca:49211" }]

[experimental.acme]
email = "joakim.soderlund@gmail.com"
registry_path = "/certs"
